"""updated service and provider service

Revision ID: 090268f5d53a
Revises: 597915cdf573
Create Date: 2024-05-31 22:58:03.112499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090268f5d53a'
down_revision = '597915cdf573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['provider_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
