"""Added latitude and longitude columns

Revision ID: 26be9291d26f
Revises: 4ae760ccfa3a
Create Date: 2024-06-10 13:39:05.389215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26be9291d26f'
down_revision = '4ae760ccfa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
