"""renamed location

Revision ID: 333d6d11b4c6
Revises: 95cd8952c9a5
Create Date: 2024-06-19 13:22:56.626259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333d6d11b4c6'
down_revision = '95cd8952c9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('county')

    # ### end Alembic commands ###
