"""empty message

Revision ID: 3653bfa8e574
Revises: 6e0ff59b1695
Create Date: 2024-03-27 01:22:18.666106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3653bfa8e574'
down_revision = '6e0ff59b1695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('national_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('national_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
