"""Add cascading deletes

Revision ID: 38548547372b
Revises: d7af429bcfd7
Create Date: 2024-05-24 13:18:51.871721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38548547372b'
down_revision = 'd7af429bcfd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.drop_constraint('provider_services_provider_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('provider_services_service_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['provider_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('services_provider_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['provider_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('services_provider_id_fkey', 'users', ['provider_id'], ['id'])

    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('provider_services_service_id_fkey', 'services', ['service_id'], ['id'])
        batch_op.create_foreign_key('provider_services_provider_id_fkey', 'users', ['provider_id'], ['id'])

    # ### end Alembic commands ###
