"""updated service and provider service

Revision ID: 597915cdf573
Revises: 38548547372b
Create Date: 2024-05-31 21:24:53.983337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597915cdf573'
down_revision = '38548547372b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('services_provider_id_fkey', type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('services_provider_id_fkey', 'users', ['provider_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
