"""added county id to user table

Revision ID: 69daec3066c5
Revises: 0001ca6aa1bd
Create Date: 2024-06-21 01:33:26.089907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69daec3066c5'
down_revision = '0001ca6aa1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'counties', ['county_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('services_provider_id_fkey', type_='foreignkey')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'counties', ['county_id'], ['id'])
        batch_op.drop_column('county')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('county_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('services_provider_id_fkey', 'users', ['provider_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('provider_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
