"""replaced county id column with county name

Revision ID: 6c330554b3ce
Revises: c1ca10c0c35f
Create Date: 2024-06-21 07:29:00.526555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c330554b3ce'
down_revision = 'c1ca10c0c35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'counties', ['county_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('county_id')

    # ### end Alembic commands ###
