"""replaced county id column with county name

Revision ID: c1ca10c0c35f
Revises: 69daec3066c5
Create Date: 2024-06-21 07:24:00.435714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ca10c0c35f'
down_revision = '69daec3066c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(), nullable=True))
        batch_op.drop_constraint('users_county_id_fkey', type_='foreignkey')
        batch_op.drop_column('county_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_county_id_fkey', 'counties', ['county_id'], ['id'])
        batch_op.drop_column('county')

    # ### end Alembic commands ###
