"""made relationship between county and services

Revision ID: cfd0b7c4b176
Revises: 333d6d11b4c6
Create Date: 2024-06-19 15:20:15.396601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd0b7c4b176'
down_revision = '333d6d11b4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'counties', ['county_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('county_id')

    # ### end Alembic commands ###
