"""updated service and provider service

Revision ID: e16840e029ad
Revises: 090268f5d53a
Create Date: 2024-05-31 23:08:51.635191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16840e029ad'
down_revision = '090268f5d53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint('services_provider_id_fkey', type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('services_provider_id_fkey', 'users', ['provider_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
