"""Add uids column

Revision ID: e8d7e4a3f8f0
Revises: 90d606b00228
Create Date: 2024-05-05 18:12:31.699406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d7e4a3f8f0'
down_revision = '90d606b00228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uids', sa.String(length=36), nullable=True))
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('uids')

    # ### end Alembic commands ###
